### ISSUE TITLE
Make SaveState generic

### ISSUE THREAD

**Issue by greenbear26** [techtigers-ftc/ftc-core#6]
Originally called AcrossOpModeSave.

Make it generic so that people can add whatever fields they want. This could involve making the class abstract, but it's messy with singletons. Test thouroughly

**Comment by windigo216** [comment]
Add hashmap state, mapping String->Object. Create public get+set methods. Initialize HashMap in getInstance(). Add try catch. In catch, throw Exception clearly stating the error (to not run into a NullPointer)

Add public static reset() method.
